version: '3'

services:
  database:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    env_file: ./backend/database.env
    ports:
      - "5432:5432"
  thegoonlagoon-app:
    build: ./backend
    env_file: ./backend/thegoonlagoon.env
    depends_on:
      - database
    ports:
      - "9000:9000"

volumes:
  postgres-data:


